### ISSUE TITLE
Some updates

### ISSUE THREAD

**Issue by justxi** [janvrany/bricknil#4]
@janvrany 
I added some updates to a fork of your repository: https://github.com/justxi/bricknil
Support for temperature sensors of Control+ hub, an example for all sensors in Control+ hub and minor improvements for importing classes.

**Comment by janvrany** [comment]
Nice, thanks! Would you mind opening a pull request?

**Comment by justxi** [comment]
Yes, I can create a PR.

Besides this... there is an information, that "255" should give a brake, but according to another file is seams to be "127" -> https://github.com/justxi/bricknil/blob/a7b0cd76f5c970ada6024d922f744358e8516121/bricknil/sensor/motor.py#L41, at least on the Control+ hub. I found that while testing it with the Rallycar.

I am also working on getting the new "Large Angular Position Motor" to work. I already added the device. But there are some bits which are not documented and are shown as "NA".

**Comment by janvrany** [comment]
Yeah, I've seen this. Let's open a PR and continue discussing there. Thanks!

**Comment by justxi** [comment]
-> PR -> https://github.com/janvrany/bricknil/pull/5

**Comment by justxi** [comment]
By the way... many thanks for your efforts!!! =)

**Comment by janvrany** [comment]
Cool, I'll check later in more detail and have a look at braking Thanks!

**Comment by justxi** [comment]
I also pushed the information about the Control+ "Large Angular Position" motor.
(Latest commit in my repository, but it seems to be last commit of the PR).

**Comment by janvrany** [comment]
Closing as PR #5 has just been merged in. Thanks a lot!
